<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TVSCHEDULE [
<!ELEMENT memories (memory)*> 
<!ELEMENT memory (media | subdate | donor?| subject+| location)* > 
<!ATTLIST memory tapeid IDREF #REQUIRED > 
<!ELEMENT subdate (#PCDATA) > 
<!ELEMENT donor (#PCDATA) > 
<!ELEMENT subject (#PCDATA) > 
<!ELEMENT location (place|description) > 
<!ELEMENT description (#PCDATA) > 
<!ELEMENT place (#PCDATA) > 
<!ELEMENT media EMPTY > 
<!ATTLIST media mediaid ID #REQUIRED >
]>
<memories>
<memory tapeid="B">
<subdate></subdate>
<donor></donor>
<subject></subject>
<location>
<description></description>
</location>
<media mediaid="A" />
</memory>
<memory tapeid="A">
<subdate></subdate>
<subject></subject>
<location>
<place></place>
</location>
<media mediaid="C" />
</memory>
<memory tapeid="C">
<subdate></subdate>
<subject></subject>
<location>
<place></place>
</location>
<media mediaid="B" />
</memory>
</memories>